FROM maven:3.6.0-jdk-8-alpine as builder
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
ADD . /usr/src/app
RUN mvn -q install
FROM payara/micro as target
COPY --from=builder /usr/src/app/target/psapipayara.war $DEPLOY_DIR